version: '3.9'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxes_calculator
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  backend:
    build: ./backend
    restart: always
    environment:
      MYSQL_URL: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend