CREATE TABLE users(
	id CHAR(32) NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(21) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL
);