server:
  port: 8080
 # servlet:
   # context-path: /api
  compression:
    enabled: false
  undertow:
    threads:
      worker: 64
      io: 4


spring:
  datasource:
    url: jdbc:mysql://${mysql.url:localhost:3306}/${mysql.schema:taxes_calculator}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: "${mysql.username:root}"
    password: "${mysql.password:root}"
    driver-class-name: com.mysql.cj.jdbc.Driver  #com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250 # é feito em miliseconds. O ideal é manter baixo para estorar timeout
      max-lifetime: 600000 #tempo adviso que uso conexão pode ficar aberto (19mins) - security
      maximum-pool-size: 20 #numero até o max 20 conexões com o banco de dados. O ideal é manter baixo
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      #"[hibernate.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
      "[hibernate.generate.statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379